name: Run quality checks
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
  pull_request:

jobs:
  test:
    environment: dev
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Composer install
        run: "composer install"

      - name: Run code sniffer
        run: "composer run lint"

      #   - name: Run swagger check
      #     run: php artisan l5-swagger:generate

      - name: Ensure storage directory exists
        run: mkdir -p storage

      - name: Setup Passport OAuth keys
        run: |
          printf "%s" "${{ secrets.OAUTH_PRIVATE }}" > storage/oauth-private.key
          printf "%s" "${{ secrets.OAUTH_PUBLIC }}" > storage/oauth-public.key
          chmod 600 storage/oauth-private.key storage/oauth-public.key

      - name: Debug key files
        run: |
          ls -l storage
          head -n 5 storage/oauth-private.key
          head -n 5 storage/oauth-public.key

      - name: .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run static analysis
        run: "./vendor/bin/phpstan analyse app -vvv  --memory-limit 512M"

      - name: Run linting
        run: "composer run lint"

      - name: Run unit tests
        run: "composer run test"
