name: Deploy branch to standalone DEV
run-name: ${{ github.actor }} deploying ${{ github.ref_name }} to standalone DEV

on:
  workflow_dispatch:

jobs:
  setup-standalone:
    runs-on: ubuntu-latest
    environment: dev-standalone
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}
    steps:
      - id: args
        run: |
          ARGS=""
          ARGS+="--secret id=github_token,env=GITHUB_TOKEN "
          echo "docker_build_args=$ARGS" >> "$GITHUB_OUTPUT"

  build-standalone:
    needs: setup-standalone
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-api/Chart.yaml
      environment: dev-standalone
      docker_build_args: ${{ needs.setup-standalone.outputs.docker_build_args }}
    secrets: inherit

  deploy-standalone:
    needs: build-standalone
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-standalone
      chart_path: chart/cohort-api/Chart.yaml
      git_ref: ${{ github.ref_name }}
    secrets: inherit
