name: Deploy Dev Standalone
run-name: ${{ github.actor }} triggered pipeline for Dev Standalone Deployment

on:
  workflow_dispatch:
    inputs:
        env:
            description: 'Select environment to deploy'
            required: true
            default: 'dev-standalone'
            type: choice
            options:
            - dev-standalone

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}

    steps:
      - id: args
        run: |
          ARGS=""
          ARGS+="--secret id=github_token,env=GITHUB_TOKEN "
          echo "docker_build_args=$ARGS" >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-api/Chart.yaml
      docker_build_args: ${{ needs.setup.outputs.docker_build_args }}
      environment: ${{ github.event.inputs.env }}
    secrets: inherit

  deploy-standalone:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-standalone
      chart_path: chart/cohort-api/Chart.yaml
    secrets: inherit