name: Build and deploy to DEV
run-name:  ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}

    steps:
      - name: Generate GitHub App token
        id: generate-deployment-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
          owner: HDRUK
          repositories: |
            ${{ github.event.repository.name }}

      - id: args
        run: |
          ARGS=""
          ARGS+="--build-arg GH_TOKEN=${{ steps.generate-deployment-token.outputs.token }}"
          echo "docker_build_args=${ARGS}" | tr -d '\n' >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-api/Chart.yaml
      docker_build_args: ${{ needs.setup.outputs.docker_build_args }}
      environment: dev-integrated
    secrets: inherit

  deploy-integrated:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-integrated
      chart_path: chart/cohort-api/Chart.yaml
      git_ref: dev
    secrets: inherit

  deploy-stadalone:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-standalone
      chart_path: chart/cohort-api/Chart.yaml
      git_ref: dev
    secrets: inherit